database/create_collections.js, database/setup.sh
=> Create MongoDB collections (tables) according to Entity Relation Diagram

README.md
Simple new guide to run database and routes on ruby
=> Instructions on README.md

README.md, backend-dashboard-2/app/controllers/api/v1/auth_controller.rb, backend-dashboard-2/app/controllers/api/v1/users_controller.rb, backend-dashboard-2/app/models/user.rb
Key changes:
- User model changes from (email, username, password) to (email, name)
- Endpoints are documented in `README.md` with examples
=> Update user model and document endpoints

README.md, backend-dashboard-2/app/controllers/api/v1/certificates_controller.rb, backend-dashboard-2/app/models/certificate.rb, backend-dashboard-2/config/routes.rb, backend-dashboard-2/test/controllers/certificate_controller_test.rb, backend-dashboard-2/test/fixtures/certificates.yml, backend-dashboard-2/test/models/certificate_test.rb
- Add Certificates model, controler, route
- Document /api/v1/certificates/ endpoint
- Minor endpoint documentation formating
=> Certificate endpoint

backend-dashboard-2/config/initializers/cors.rb
Just had incorrect syntax from CORS at Rails. haven't tested but should work.
=> Mistakes on syntax from cors

client/package-lock.json, client/package.json, client/src/components/CertificationRow/CertificationRow.css, client/src/components/CertificationRow/CertificationRow.tsx, client/src/components/DashboardTable/DashboardTable.css, client/src/components/DashboardTable/DashboardTable.tsx, client/src/components/Sidebar/Sidebar.tsx, client/src/components/SidebarSection/SidebarSection.css, client/src/components/SidebarSection/SidebarSection.tsx
`CertificationRow.tsx`
- Changed height
`DashboardTable.tsx`
- Changed font sizes
- Added dropdown select with `react-select` library
`Sidebar.tsx`
- Added state for selected section
`SidebarSection.tsx`
- Now it also receives selectedSection and setSelectedSection prop
- Compares the selected section with the name, if true, changes background color
- Hover animation
https://user-images.githubusercontent.com/72105206/234063978-a96d667b-890d-4ebc-b2eb-c3bb95b6233f.mov
=> Dashboard style correction

client/lib/types.ts, client/src/components/Profile/Profile.css, client/src/components/Profile/Profile.tsx, client/src/components/ProfileContainer.tsx, client/src/components/ProfileInfoCard/ProfileInfoCard.css, client/src/components/ProfileInfoCard/ProfileInfoCard.tsx, client/src/components/ProfileTeamCard/ProfileTeamCard.css, client/src/components/ProfileTeamCard/ProfileTeamCard.tsx, client/src/components/SidebarProfile/SidebarProfile.tsx, client/src/components/SidebarProfileContainer.tsx, client/src/screens/ProfileScreen/ProfileScreen.tsx
**Component**
- ProfileInfoCard.tsx
- Card to display user info and profile picture
- Props:
- user : User {name: string, last_name :string, role: string, email: string}
- Created and styled ProfileInfoCard.tsx having dynamic user
=> Profile screen and Profile Info Card

client/lib/types.ts, client/src/components/Header/Header.css, client/src/components/TeamRow/TeamRow.css, client/src/components/TeamRow/TeamRow.tsx, client/src/screens/MyTeamsScreen/MyTeamsScreen.tsx
- `TeamRow.tsx`
- Row part of a future component called TeamTable.
- `types.ts`
- Attribute added to 'User' interface.
- `MyTeamScreen.tsx`
- Temporal dummy data added in top of component to render the TeamRow component.
- Change Header title to 'My Teams' instead of 'My Team'.  
- `CertificationRow.tsx`
- Change items position to align them with the top bar of the table.
- `Header.tsx`
- Changed font-weight attribute to the text of it to a heavier one. (ik it's not part of what I had to do but me dio fomo srry)  
- `TeamRow.tsx` component created, it renders a card that contains an employee, with its name, role and a button to visit their profile.
=> (client): TeamRow component finished

client/package-lock.json, client/package.json
Pretty self explanatory methinks
=> (client) Add Axios and other package.json missing dependencies

backend-dashboard-2/config/initializers/cors.rb
changes on `backend-dashboard-2/config/initializers/cors.rb` due to clearly bat syntax
=> HotFix on CORS due to bad syntax

client/src/screens/MyTeamsScreen/MyTeamsScreen.tsx
MyTeamScreen dummy data was missing id and role
=> Fixed User Type errors

README.md, backend-dashboard-2/app/controllers/api/v1/auth_controller.rb, backend-dashboard-2/app/controllers/api/v1/certificates_controller.rb, backend-dashboard-2/app/controllers/api/v1/users_controller.rb, backend-dashboard-2/app/controllers/concerns/authentication.rb, backend-dashboard-2/app/models/user.rb
- Certificates and Users are only available to logged in users
- User fields change from (name, email) to (id, email, employee_id)
- Hotfixes:
- Instructions for setting up REACT_ROUTE variable
- Instructions to run server on public IP
=> (Back-end) Implement session tokens and conform User class to entity diagram

client/lib/types.ts, client/src/components/DashboardTable/DashboardTable.tsx, client/src/components/DashboardTableContainer.tsx, client/src/components/Profile/Profile.css, client/src/components/Profile/Profile.tsx, client/src/components/ProfileContainer.tsx, client/src/components/ProfileInfoCard/ProfileInfoCard.tsx, client/src/components/ProfileTeamCard/ProfileTeamCard.css, client/src/components/ProfileTeamCard/ProfileTeamCard.tsx
**Component**
- ProfileTeamCard.tsx
- Card to display user table with the teams the user is on, including the name of the manager
- Props:
- teamWithManager[ ]: 
- team: Team { name: string, id: string }
- manager: User { id: string, name: string, last_name: string, role: string, email: string }
Created and styled ProfileTeamCard.tsx having dynamic teams
Implemented interface profile info to simulate the response from the server and pass it along through the components
Corrected use of needless interface Certificates in DashboardTable.tsx
=> Profile team card

client/lib/types.ts, client/src/components/TeamCard/TeamCard.css, client/src/components/TeamCard/TeamCard.tsx, client/src/components/TeamRow/TeamRow.css, client/src/components/TeamRow/TeamRow.tsx, client/src/components/TeamTable/TeamTable.tsx, client/src/components/TeamTableContainer.tsx, client/src/screens/MyTeamsScreen/MyTeamsScreen.tsx
- `TeamTable.tsx` and `TeamTableContainer.tsx`
- TeamTable components now with stuff on it and working as expected.
- `TeamWithEmployeesManager` interface created on container component.
- `TeamCard.css`
- Changed height values of this component.
- `MyTeamScreen.tsx`
- Removed all other components I had and put the TeamTableContainer on it.
- Dummy Data
- Removed all the dummy data that were on non-container components. 
- `TeamTable.tsx` component created, renders dynamically a list of teams that a manager has.
=> Team table

client/lib/types.ts, client/src/components/TeamCard/TeamCard.tsx, client/src/components/TeamTable/TeamTable.tsx
- Fixing error where children of tables don't have a key assigned
- Adding back TeamWithManager type
=> Team card-row error fix

backend-dashboard-2/config/application.rb, backend-dashboard-2/config/environments/development.rb
Disable SSL requirement for cookies except in `backend-dashboard-2/config/environments/production.rb`
=> Disable secure connection requirement

client/src/components/ProfileCertificationCard/ProfileCertificationCard.css, client/src/components/ProfileCertificationCard/ProfileCertificationCard.tsx, client/src/components/ProfileCertifications/ProfileCertifications.css, client/src/components/ProfileCertifications/ProfileCertifications.tsx, client/src/components/Sidebar/Sidebar.css, client/src/screens/DashboardScreen/DashboardScreen.css
`ProfileCertificationCard.tsx`
- Receives a certificate as a prop
- Styled
`ProfileCertifications.tsx`
- Renders `ProfileCertificationCard.tsx` with a map
- Created `ProfileCertificationCard.tsx` component
- Added `ProfileCertificationCard.tsx` to the `ProfileCertifications.tsx`
- Styled `ProfileCertificationCard.tsx` 
- Changed sidebar and screen size (temporal)
=> Profile certifications card

client/src/components/Profile/Profile.tsx, client/src/components/ProfileCertificationCard/ProfileCertificationCard.css, client/src/components/ProfileCertificationCard/ProfileCertificationCard.tsx, client/src/components/ProfileCertifications/ProfileCertifications.css, client/src/components/ProfileCertifications/ProfileCertifications.tsx, client/src/components/ProfileContainer.tsx, client/src/components/Sidebar/Sidebar.css, client/src/screens/DashboardScreen/DashboardScreen.css
`ProfileContainer.tsx`
- Added more data to dummy json
`ProfileCertifications.tsx`
- Receives user and certifications as props
- Renders `ProfileCertificationCard.tsx` components
- Styled
=> Profile certifications

backend-dashboard-2/app/controllers/api/v1/auth_controller.rb, backend-dashboard-2/app/controllers/api/v1/employees_controller.rb, backend-dashboard-2/app/controllers/api/v1/users_controller.rb, backend-dashboard-2/app/models/employee.rb, backend-dashboard-2/app/models/user.rb, backend-dashboard-2/config/routes.rb, backend-dashboard-2/test/controllers/employees_controller_test.rb, backend-dashboard-2/test/fixtures/employees.yml, backend-dashboard-2/test/models/employee_test.rb
Major and very ultra mostimportant changes:
a GET output looks like this:
```JSON
[
{
"_id": "amaj8uj645l",
"created_at": "2023-04-27T20:16:54.358Z",
"email": "amaj@ibm.com",
"id": "amaj8uj645l",
"last_name": "Juarez",
"name": "Amaranta",
"role": "Software Manger",
"updated_at": "2023-04-27T20:16:54.358Z"
}
]
```
If it's not there you'll get this error:
=> Employee deployed

client/src/components/Header/Header.css, client/src/components/Profile/Profile.tsx, client/src/components/ProfileCertificationCard/ProfileCertificationCard.css, client/src/components/ProfileCertifications/ProfileCertifications.css, client/src/screens/ProfileScreen/ProfileScreen.tsx
- `Header.tsx` `ProfileCertificationCard.tsx` `ProfileCertification.tsx`
- Changed some of the styling on these components 
- `ProfileCertificationCard.tsx` component now adapting to different screen sizes, avoiding overflow on screen.
=> (client): certifications cards now being responsive

client/src/components/Employees/Employees.css, client/src/components/Employees/Employees.tsx, client/src/components/EmployeesContainer.tsx, client/src/components/EmployeesTable/EmployeesTable.css, client/src/components/EmployeesTable/EmployeesTable.tsx, client/src/screens/AllEmployeesScreen/AllEmployeesScreen.tsx
- `EmployeesContainer.tsx`
- EmployeeContainer created and now inside `EmployeesScreen.tsx`.
- No dummy data yet.
-  `Employees.tsx`
- Rendering a container with a filter bar at top and the sections of the future EmployeesRow component.
- First components created for Employees Screen.
=> (client): Employees.tsx and EmployeesContainer.tsx components created

backend-dashboard-2/app/controllers/api/v1/teams_controller.rb, backend-dashboard-2/app/models/employee.rb, backend-dashboard-2/app/models/employee_team.rb, backend-dashboard-2/app/models/team.rb
```JSON
{
"teams": [
{
"team": {
"id": "644c25aee64d1e6d26836799",
"name": "Back-end Management"
},
"employees": [
{
"id": "alyxita",
"name": "Alyx",
"last_name": "Miranda",
"email": "alyx@ibm.com",
"role": "TopGamer"
},
{
"id": "cr7id",
"name": "Cristiano",
"last_name": "Ronaldo",
"email": "cr7@ibm.com",
"role": "Senior Manager"
}
],
"manager": [
{
"id": "cameki0-8",
"name": "Camello",
"last_name": "Petrolero",
"email": "camello@ibm.com",
"role": "Camello Manager"
}
]
},
{
"team": {
"id": "644c25dbe64d1e6d2683679a",
"name": "IBM Testing"
},
"employees": [],
"manager": []
},
{
"team": {
"id": "644c25eae64d1e6d2683679b",
"name": "Let's say they have Game dev team"
},
"employees": [],
"manager": []
}
]
}
```
Current Json format for show all employees endpoint from …
=> team json endpoint GET /teams

backend-dashboard-2/app/controllers/api/v1/auth_controller.rb
- return `unauthorized` when employee is not found.
- return `newUser` JSON field (values 0 or 1) if user was created or existing
=> (Back end) Turn Auth CTRL nested ifs into guard clauses, change status codes and JSON

client/package-lock.json, client/package.json, client/src/App.tsx, client/src/components/LoginContainer.tsx, client/src/contexts/UserContext.tsx
- Login Container now calls the login endpoint to do the authentication
- Context and local storage are refreshed with the firebase idToken
- Navigating to dashboard screen
https://user-images.githubusercontent.com/74514519/236042495-3f29836a-b35a-4502-a063-08b4f13ff22c.mp4
=> Login with server

server/app/controllers/api/v1/certificates_controller.rb, server/app/controllers/api/v1/employees_controller.rb, server/app/models/certificate.rb, server/config/routes.rb
ROUTE: `GET    /api/v1/employees/myteamviewer(.:format)`
```JSON
{
"teams": [
{
"team": {
"id": "644c25aee64d1e6d26836799",
"name": "Back-end Management"
},
"manager": {
"id": "cameki0-8",
"name": "Camello",
"last_name": "Petrolero",
"email": "camello@ibm.com",
"role": "Camello Manager"
}
}
]
}
```
=> My teams connection

.github/workflows/deploy.yml
=> (devops) rename deploy job

client/src/components/ProfileContainer.tsx, client/src/components/SidebarProfileContainer.tsx
Corrected null return in Profile.
Corrected Sidebar Container endpoint
=> Profile Null Error Correction

client/src/components/Sidebar/Sidebar.tsx, client/src/components/SidebarProfileContainer.tsx, client/src/components/TeamCard/TeamCard.tsx, client/src/components/TeamTableContainer.tsx, server/app/controllers/api/v1/employees_controller.rb, server/app/models/employee.rb
- TeamTableContainer.tsx fetches teams info from the backend
**Backend Model Changes**
- employee.teams returns team.info, team.manager and team.employees
- employee.teamWithManager  returns team.info and team.manager
=> Team table container connection

server/app/controllers/api/v1/employees_controller.rb
- Change `@employee` for `employee` in employees controller `index` function.
=> (backend) fix /employees

server/app/controllers/api/v1/employees_controller.rb
Reverts 13th-office/IBM-SkillBoard#150
This endpoint change was unnecessary and breaks the current state of the front end
=> Revert "(backend) fix /employees"

client/src/components/DashboardTable/DashboardTable.tsx, client/src/components/EmployeesContainer.tsx, client/src/components/Loading/Loading.css, client/src/components/Loading/Loading.tsx, client/src/components/ProfileContainer.tsx, client/src/components/SidebarProfileContainer.tsx, client/src/components/TeamTableContainer.tsx
- `Loading.tsx`
- Created loading animation
- type prop is true when is a main loading, if secundary loading false
- mainColor is true when white color, false when blue color
https://github.com/13th-office/IBM-SkillBoard/assets/72105206/d3af84ae-6a7a-4f71-8dfd-0ee278b4bba1
=> Loading Animation

client/lib/types.ts, client/src/components/CertificationRow/CertificationRow.tsx, client/src/components/DashboardTable/DashboardTable.tsx, client/src/components/DashboardTableContainer.tsx, client/src/components/EmployeesContainer.tsx, client/src/components/Loading/Loading.css, client/src/components/Loading/Loading.tsx, client/src/components/ProfileCertifications/ProfileCertifications.tsx, client/src/components/ProfileContainer.tsx, client/src/components/SidebarProfileContainer.tsx, client/src/components/TeamTableContainer.tsx
- `DashboardTableContainer.tsx`
- Deleted dummy data
- Fetching data from backend
-  `DashboardTable.tsx`
- Renders data from container
- Receives states from fetch for loading, error or data
- Selector is independent from loading
- Completed connection with backend for this screen, selector is independent from loading
https://github.com/13th-office/IBM-SkillBoard/assets/72105206/8d5b7280-7d90-4e16-9ea2-b0368ca6aac4
=> Dashboard Conection with Backend

server/app/models/employee.rb, server/app/models/team.rb
Null Employees and Teams coukd be created
=> changes on endpoints to  to not receive empty values

server/app/controllers/api/v1/employees_controller.rb, server/config/routes.rb
- Added new endpoint `/search/employees(/:search_term)`
- `search_term` is an optional parameter and the endpoint will search all employees whose name or last name match the term
- if no param is passed, returns all employees
=> Search Endpoint

client/src/components/EmployeesContainer.tsx
=> (client): fixed a visual bug found in AllEmployeesScreen

client/src/components/Employees/Employees.css, client/src/components/Employees/Employees.tsx, client/src/components/EmployeesContainer.tsx, client/src/components/EmployeesSearchBar/EmployeeSearchBar.css, client/src/components/EmployeesSearchBar/EmployeeSearchBar.tsx
- Search bar in `Employees.tsx` was separated into its own component
- Users can now search employees based on their names or last names
**Component**
- `EmployeesSearchBar.tsx` receives as props a function that will be what the onChange function of the search bar does
- ` changeTerm: (change: string) => void; `
**To Do**
- Throttling function to reduce the requests usage
https://github.com/13th-office/IBM-SkillBoard/assets/74514519/f34f7315-774e-42c2-826d-102cce5feb82
=> Search functionality

client/package-lock.json, client/package.json, client/src/components/EmployeesSearchBar/EmployeeSearchBar.tsx
- Search is done 0.5 seconds after the user stops writing
https://github.com/13th-office/IBM-SkillBoard/assets/74514519/16856cdb-5785-4832-abe5-872dce5d500b
=> Search employee debounce
